name: Java Workflow

on:
  workflow_dispatch:
  push:
    branches: main

env:
  Grussformel: Gruezi
jobs:
  build-test:
    runs-on: ubuntu-latest
    needs: console_writer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Build and Test with Maven
        run: mvn -B clean verify
        
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/
          
  linter:
    runs-on: ubuntu-latest
    needs: console_writer
    if: always()
    strategy:
      matrix:
        version: [11, 17]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${( matrix.version )}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${( matrix.version }}'
        
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-results
          path: target/checkstyle-result.xml
        
  console_writer:
    runs-on: ubuntu-latest
    if: always()
    env:
      Begrüsster: miteinand

    steps:
     
      - name: Print my stuff
        env:
          Passwordnutzen: exploits
        run: echo $Grussformel $Begrüsster, das Passwort für $Passwordnutzen ist $Password.
      
      
        
